platform :ios, '9.0'

use_frameworks!

target 'SwiftEntryKitDemo' do
	pod 'SwiftEntryKit', :path => '../'
end

target 'SwiftEntryKitTests' do
	pod 'SwiftEntryKit', :path => '../'
    pod 'Quick', '1.3.4'
    pod 'Nimble', '7.3.2'
end
