platform :ios, '9.0'

use_frameworks!

target 'SwiftEntryKit_Example' do
  pod 'SwiftEntryKit', :path => '../'

  target 'SwiftEntryKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
